import { useState } from 'react';
// SpotterEmbed is the React wrapper for ThoughtSpot's conversational AI component.
// It renders inside an iframe managed by the Visual Embed SDK.
import { SpotterEmbed } from '@thoughtspot/visual-embed-sdk/react';
// EmbedEvent exposes lifecycle event constants (Init, Load, Error, etc.)
import { EmbedEvent } from '@thoughtspot/visual-embed-sdk';
// CustomisationsInterface types the object that controls branding — icon sprites,
// string overrides, and string ID overrides for specific UI copy slots.
import type { CustomisationsInterface } from '@thoughtspot/visual-embed-sdk';

// The Model (Worksheet) GUID that Spotter will query against.
// Set VITE_TS_WORKSHEET_ID in your .env file.
const WORKSHEET_ID = import.meta.env.VITE_TS_WORKSHEET_ID;

// ---------------------------------------------------------------------------
// Quinyx brand palette — derived from their confirmed Petroleum primary #004851.
//
//   #004851  Petroleum       primary brand / headings / buttons
//   #006B7D  Petroleum mid   lighter teal for hover states
//   #EAF3F4  Teal tint light panel and card backgrounds
//   #F4FAFB  Teal tint pale  page root background
//   #1A1A1A  Text dark       body copy on light backgrounds
//   #FFFFFF  White           copy on petroleum backgrounds
//   #C5DEDE  Border          subtle separator lines
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// BRANDED_CUSTOMIZATIONS — applied only in "Branded Spotter" mode.
//
// CustomisationsInterface has three top-level sections:
//   style        -> CSS variable overrides and optional external stylesheet URL
//   iconSpriteUrl -> URL to an SVG sprite replacing the default TS icon set
//   content      -> string and stringID overrides for UI copy
// ---------------------------------------------------------------------------
const BRANDED_CUSTOMIZATIONS: CustomisationsInterface = {
  // Replace the default ThoughtSpot icon set with a custom SVG sprite.
  iconSpriteUrl: 'https://cdn.jsdelivr.net/gh/datasketch45/public_assets/custom_icons.svg',

  style: {
    customCSS: {
      variables: {
        // --- Page & panel backgrounds ---
        // Root background: pale teal tint matching Quinyx's clean light aesthetic
        '--ts-var-root-background':                       '#F4FAFB',
        // Chat conversation bubble background
        '--ts-var-spotter-prompt-background':             '#EAF3F4',
        // Chat input box background
        '--ts-var-spotter-input-background':              '#FFFFFF',

        // --- Typography ---
        // Global text color — dark charcoal for readability on light backgrounds
        '--ts-var-root-color':                            '#1A1A1A',

        // --- Buttons ---
        // Primary CTA — Quinyx Petroleum
        '--ts-var-button--primary-background':            '#004851',
        '--ts-var-button--primary-color':                 '#FFFFFF',
        // Secondary buttons — light teal tint with petroleum text
        '--ts-var-button--secondary-background':          '#EAF3F4',
        '--ts-var-button--secondary-color':               '#004851',
        '--ts-var-button--secondary--hover-background':   '#C5DEDE',

        // --- Chart / viz cards generated by Spotter ---
        '--ts-var-viz-background':                        '#FFFFFF',
        '--ts-var-viz-border-radius':                     '8px',
        '--ts-var-viz-title-color':                       '#004851',
        '--ts-var-viz-description-color':                 '#4A6B70',

        // --- Navigation / header bar inside the iframe ---
        '--ts-var-nav-background':                        '#004851',
        '--ts-var-nav-color':                             '#FFFFFF',
      },
    },
  },

  content: {
    // strings: global key->value replacements across all embed UI text.
    strings: {
      'Spotter':     'Abby Analytics',
      'ThoughtSpot': 'Abby Analytics',
      "Let's make sense of your data together": 'Ask me anything about your data',
    },

    // stringIDs: targeted overrides using ThoughtSpot's internal i18n keys.
    // Takes precedence over generic string replacements for specific copy slots.
    stringIDs: {
      // Landing-page hero greeting shown before the first message
      'spotter.newChatPrompt.landingPage.title': "Hi, I\u2019m Agent Abby, your data analyst!",
    },
  },
};

// ---------------------------------------------------------------------------
// BRANDED_CHAT_CONFIG — controls Spotter's chat card branding (spotterChatConfig).
//
// SpotterChatViewConfig properties:
//   hideToolResponseCardBranding  -> hides the TS logo/icon inside AI response cards
//   toolResponseCardBrandingLabel -> replaces the "ThoughtSpot" label in response cards
//   spotterFileUploadEnabled      -> allows users to upload files in the chat input
// ---------------------------------------------------------------------------
const BRANDED_CHAT_CONFIG = {
  // Suppress the ThoughtSpot logo from appearing inside tool-response cards
  hideToolResponseCardBranding: true,
  // Label shown in the header of each AI-generated response card
  toolResponseCardBrandingLabel: 'WF Agent',
  // Enable the file-upload button in the Spotter chat input area
  spotterFileUploadEnabled: true,
};

// ---------------------------------------------------------------------------
// SpotterPage — renders a toggle bar above the SpotterEmbed iframe.
//
// State:
//   branded (false) -> vanilla Spotter with no customizations
//   branded (true)  -> fully branded embed (BRANDED_CUSTOMIZATIONS + BRANDED_CHAT_CONFIG)
//
// The button label always shows where clicking will take you next:
//   showing Basic   -> button says "Branded Spotter"
//   showing Branded -> button says "Basic Spotter"
// ---------------------------------------------------------------------------
export default function SpotterPage() {
  const [branded, setBranded] = useState(false);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>

      {/* Toggle bar — shows current mode label and a button to switch */}
      <div style={branded ? styles.barBranded : styles.bar}>
        <span style={branded ? styles.labelBranded : styles.label}>
          {branded ? 'Branded Spotter' : 'Basic Spotter'}
        </span>
        <button
          style={branded ? styles.buttonBranded : styles.button}
          onClick={() => setBranded((b) => !b)}
        >
          {branded ? 'Basic Spotter' : 'Branded Spotter'}
        </button>
      </div>

      {/*
        SpotterEmbed props:
          worksheetId              -> the Model/Worksheet GUID Spotter runs queries against
          frameParams              -> sets the iframe dimensions
          updatedSpotterChatPrompt -> opts in to the updated chat input UI (SDK 1.39+)
          customizations           -> branding overrides (CSS, icons, strings); undefined in basic mode
          spotterChatConfig        -> chat card branding config; undefined in basic mode
          onInit / onLoad / onError -> lifecycle event callbacks logged to the console
      */}
      <SpotterEmbed
        worksheetId={WORKSHEET_ID}
        frameParams={{ height: '720px' }}
        updatedSpotterChatPrompt={true}
        customizations={branded ? BRANDED_CUSTOMIZATIONS : undefined}
        spotterChatConfig={branded ? BRANDED_CHAT_CONFIG : undefined}
        onInit={() => console.log(EmbedEvent.Init)}
        onLoad={() => console.log(EmbedEvent.Load)}
        onError={(e: unknown) => console.error('SpotterEmbed error:', e)}
      />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Inline styles — kept as a typed record so React accepts them without cast.
// The branded bar mirrors the Quinyx Petroleum color so the chrome matches
// the embed theme the moment you switch modes.
// ---------------------------------------------------------------------------
const styles: Record<string, React.CSSProperties> = {
  // Basic mode bar — neutral light gray
  bar: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 16px',
    background: '#f8f8f8',
    borderBottom: '1px solid #e2e2e2',
  },
  // Branded mode bar — Quinyx Petroleum so the chrome matches the embed
  barBranded: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 16px',
    background: '#004851',
    borderBottom: '1px solid #003840',
  },
  label: {
    fontWeight: 600,
    fontSize: 14,
    color: '#333',
  },
  // White label on petroleum bar
  labelBranded: {
    fontWeight: 600,
    fontSize: 14,
    color: '#FFFFFF',
  },
  button: {
    padding: '6px 16px',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    borderRadius: 6,
    border: '1px solid #1e6bf7',
    background: '#1e6bf7',
    color: '#fff',
  },
  // Inverted button — white outline on petroleum background
  buttonBranded: {
    padding: '6px 16px',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    borderRadius: 6,
    border: '1px solid #FFFFFF',
    background: 'transparent',
    color: '#FFFFFF',
  },
};
